language: ruby
rvm: 1.8.7
addons:
  firefox: "23.0"
before_install:
 - export DISPLAY=:99.0
 - sh -e /etc/init.d/xvfb start
script:
 - cd static
 - bundle install --deployment
 - bundle exec ttr webdriverurl=firefox verbose
